/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hectorp;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author hecto
 */
public class provedor extends javax.swing.JInternalFrame {
Connection conn = null;
    Conexion Conect = new Conexion();
    String qry = "";
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form provedor
     */
    public provedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        correo_prov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre_prov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nit_prov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefono_prov = new javax.swing.JTextField();
        txtCV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Correo Del Proveedor");

        jLabel6.setText("Categoria");

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insumos", "Mercaderia", "Papeleria" }));

        jLabel1.setText("ID Proveedores");

        jLabel2.setText("Nombre del Proveedor");

        jLabel3.setText("NIT Proveedor");

        jLabel4.setText("Telefono Proveedor");

        jLabel7.setText("Codifo De Validacion");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Moficar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtCV))
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(correo_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(113, 113, 113)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addGap(62, 62, 62))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nombre_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nit_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addComponent(telefono_prov))
                            .addGap(10, 10, 10)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(74, 74, 74))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombre_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nit_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefono_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(correo_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: guardar de
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Modificar la consulta para incluir el campo codigo_validacion
        qry = "INSERT INTO proveedores (nombre_prov, nit_prov, telefono_prov, correo_prov, categorias_prov, codigo_validacion) VALUES (?,?,?,?,?,?)";

        PreparedStatement ps = conn.prepareStatement(qry);

        ps.setString(1, nombre_prov.getText());
        ps.setString(2, nit_prov.getText());
        ps.setString(3, telefono_prov.getText());
        ps.setString(4, correo_prov.getText());
        String categoriasselect = (String) categoria.getSelectedItem();
        ps.setString(5, categoriasselect);

        // Aquí se agrega el valor del código de validación
        ps.setString(6, txtCV.getText()); 

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Se ha creado el registro exitosamente");
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: modificar
       try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Modificar la consulta para actualizar los campos, incluyendo codigo_validacion
        qry = "UPDATE proveedores SET nombre_prov = ?, nit_prov = ?, telefono_prov = ?, correo_prov = ?, categorias_prov = ?, codigo_validacion = ? WHERE id_prov = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        ps.setString(1, nombre_prov.getText());
        ps.setString(2, nit_prov.getText());
        ps.setString(3, telefono_prov.getText());
        ps.setString(4, correo_prov.getText());
        String categoriasselect = (String) categoria.getSelectedItem();
        ps.setString(5, categoriasselect);



        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Se ha actualizado el registro exitosamente");
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: eliminiar
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Consulta SQL para eliminar un proveedor por su id_prov
        qry = "DELETE FROM proveedores WHERE id_prov = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        // Suponiendo que id_prov es el identificador del proveedor que deseas eliminar
        ps.setInt(1, Integer.parseInt(txtID.getText())); // Aquí se pasa el ID del proveedor a eliminar

        int rowsDeleted = ps.executeUpdate(); // Ejecuta la consulta

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(null, "Se ha eliminado el registro exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el registro con ese ID");
        }
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:consultar
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Consulta SQL para buscar un proveedor por su codigo_validacion
        qry = "SELECT nombre_prov, nit_prov, telefono_prov, correo_prov, categorias_prov FROM proveedores WHERE codigo_validacion = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        // Suponiendo que el código de validación se ingresa en un campo de texto
        ps.setString(1, txtCV.getText());

        ResultSet rs = ps.executeQuery(); // Ejecuta la consulta

        if (rs.next()) {
            // Obtener los valores del proveedor
            String nombre = rs.getString("nombre_prov");
            String nit = rs.getString("nit_prov");
            String telefono = rs.getString("telefono_prov");
            String correo = rs.getString("correo_prov");
            String categoria = rs.getString("categorias_prov");

            // Muestra la información del proveedor
            JOptionPane.showMessageDialog(null, 
                "Nombre: " + nombre + "\n" +
                "NIT: " + nit + "\n" +
                "Teléfono: " + telefono + "\n" +
                "Correo: " + correo + "\n" +
                "Categoría: " + categoria);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún proveedor con ese código de validación");
        }
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}


    }//GEN-LAST:event_jButton4ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField correo_prov;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nit_prov;
    private javax.swing.JTextField nombre_prov;
    private javax.swing.JTextField telefono_prov;
    private javax.swing.JTextField txtCV;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
