/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author hector Lopez
 */
public class provedor extends javax.swing.JInternalFrame {
Connection conn = null;
    Conexion Conect = new Conexion();
    String qry = "";
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form provedor
     */
    public provedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        correo_prov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre_prov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nit_prov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefono_prov = new javax.swing.JTextField();
        txtCV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtmGuardar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Correo Del Proveedor");

        jLabel6.setText("Categoria");

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insumos", "Mercaderia", "Papeleria" }));
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Proveedores");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del Proveedor");

        jLabel3.setText("NIT Proveedor");

        jLabel4.setText("Telefono Proveedor");

        jLabel7.setText("Codigo De Validacion");

        BtmGuardar.setText("Guardar");
        BtmGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmGuardarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Modificar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar ");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnConsultar.setText("Consultar");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BtmGuardar)
                .addGap(33, 33, 33)
                .addComponent(BtnGuardar)
                .addGap(30, 30, 30)
                .addComponent(BtnEliminar)
                .addGap(35, 35, 35)
                .addComponent(BtnConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txtCV))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombre_prov, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(nit_prov)
                                .addComponent(telefono_prov))
                            .addComponent(correo_prov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {categoria, correo_prov, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, nit_prov, nombre_prov, telefono_prov, txtCV, txtID});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nit_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(telefono_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nombre_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correo_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtmGuardar)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnConsultar))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtmGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmGuardarActionPerformed
        // TODO add your handling code here: guardar de
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Modificar la consulta para incluir el campo codigo_validacion
        qry = "INSERT INTO proveedores (nombre_prov, nit_prov, telefono_prov, correo_prov, categorias_prov, codigo_validacion) VALUES (?,?,?,?,?,?)";

        PreparedStatement ps = conn.prepareStatement(qry);

        ps.setString(1, nombre_prov.getText());
        ps.setString(2, nit_prov.getText());
        ps.setString(3, telefono_prov.getText());
        ps.setString(4, correo_prov.getText());
        String categoriasselect = (String) categoria.getSelectedItem();
        ps.setString(5, categoriasselect);

        // Aquí se agrega el valor del código de validación
        ps.setString(6, txtCV.getText()); 

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Se ha creado el registro exitosamente");
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}


    }//GEN-LAST:event_BtmGuardarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here: modificar
       try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Modificar la consulta para actualizar los campos, incluyendo codigo_validacion
        qry = "UPDATE proveedores SET nombre_prov = ?, nit_prov = ?, telefono_prov = ?, correo_prov = ?, categorias_prov = ?, codigo_validacion = ? WHERE id_prov = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        ps.setString(1, nombre_prov.getText());
        ps.setString(2, nit_prov.getText());
        ps.setString(3, telefono_prov.getText());
        ps.setString(4, correo_prov.getText());
        String categoriasselect = (String) categoria.getSelectedItem();
        ps.setString(5, categoriasselect);



        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Se ha actualizado el registro exitosamente");
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here: eliminiar
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Consulta SQL para eliminar un proveedor por su id_prov
        qry = "DELETE FROM proveedores WHERE id_prov = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        // Suponiendo que id_prov es el identificador del proveedor que deseas eliminar
        ps.setInt(1, Integer.parseInt(txtID.getText())); // Aquí se pasa el ID del proveedor a eliminar

        int rowsDeleted = ps.executeUpdate(); // Ejecuta la consulta

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(null, "Se ha eliminado el registro exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el registro con ese ID");
        }
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}

    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        // TODO add your handling code here:consultar
        try {
    conn = Conect.getConnection();
    if (conn != null) {
        // Consulta SQL para buscar un proveedor por su codigo_validacion
        qry = "SELECT nombre_prov, nit_prov, telefono_prov, correo_prov, categorias_prov FROM proveedores WHERE codigo_validacion = ?";

        PreparedStatement ps = conn.prepareStatement(qry);

        // Suponiendo que el código de validación se ingresa en un campo de texto
        ps.setString(1, txtCV.getText());

        ResultSet rs = ps.executeQuery(); // Ejecuta la consulta

        if (rs.next()) {
            // Obtener los valores del proveedor
            String nombre = rs.getString("nombre_prov");
            String nit = rs.getString("nit_prov");
            String telefono = rs.getString("telefono_prov");
            String correo = rs.getString("correo_prov");
            String categoria = rs.getString("categorias_prov");

            // Muestra la información del proveedor
            JOptionPane.showMessageDialog(null, 
                "Nombre: " + nombre + "\n" +
                "NIT: " + nit + "\n" +
                "Teléfono: " + telefono + "\n" +
                "Correo: " + correo + "\n" +
                "Categoría: " + categoria);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún proveedor con ese código de validación");
        }
    }

} catch (SQLException sqle) {
    System.out.println(sqle.getMessage());
} finally {
    try {
        conn.close();
    } catch (SQLException sqle) {
        System.out.println(sqle.getMessage());
    }
}


    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtmGuardar;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField correo_prov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nit_prov;
    private javax.swing.JTextField nombre_prov;
    private javax.swing.JTextField telefono_prov;
    private javax.swing.JTextField txtCV;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
