CREATE TABLE proveedores (
    id_prov NUMBER GENERATED BY DEFAULT AS IDENTITY, -- Identificador único automático
    nombre_prov VARCHAR2(100) NOT NULL, -- Nombre del proveedor
    nit_prov VARCHAR2(20) NOT NULL, -- NIT del proveedor
    telefono_prov VARCHAR2(15), -- Teléfono del proveedor
    correo_prov VARCHAR2(100), -- Correo electrónico del proveedor
    categorias_prov VARCHAR2(50), -- Categoría del proveedor
    codigo_validacion VARCHAR2(10), -- Código de validación
    PRIMARY KEY (id_prov) -- Llave primaria
);
select * from USUARIO;
CREATE TABLE finanzas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY, -- Identificador único automático
    nombre VARCHAR2(100) NOT NULL, -- Nombre del empleado
    apellido VARCHAR2(100) NOT NULL, -- Apellido del empleado
    numero_empleado VARCHAR2(20) NOT NULL, -- Número de empleado
    correo VARCHAR2(100) NOT NULL, -- Correo electrónico
    telefono VARCHAR2(15), -- Teléfono del empleado
    fecha_contratacion DATE NOT NULL, -- Fecha de contratación
    salario NUMBER(10, 2) NOT NULL, -- Salario del empleado
    genero VARCHAR2(10), -- Género del empleado
    estado VARCHAR2(50), -- Estado actual del empleado (activo, inactivo, etc.)
    PRIMARY KEY (id) -- Llave primaria
);

select * from finanzas;
CREATE TABLE RRHH (
    ID NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    numero_empleado VARCHAR2(20) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    fecha_contratacion DATE NOT NULL,
    salario NUMBER(10, 2) NOT NULL,
    genero VARCHAR2(10) NOT NULL,
    estado VARCHAR2(20) NOT NULL
);
CREATE TABLE Ventas (
    ID NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    numero_empleado VARCHAR2(20) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    fecha_contratacion DATE NOT NULL,
    salario NUMBER(10, 2) NOT NULL,
    genero VARCHAR2(10) NOT NULL,
    estado VARCHAR2(20) NOT NULL
);
CREATE TABLE RRHH (
    ID NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    numero_empleado VARCHAR2(20) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    fecha_contratacion DATE NOT NULL,
    salario NUMBER(10, 2) NOT NULL,
    genero VARCHAR2(10) NOT NULL,
    estado VARCHAR2(20) NOT NULL
);


