select * from usuario;
SELECT * FROM GLOBAL_NAME;
SELECT name FROM v$database;

drop table usuario;
CREATE TABLE usuario (
    nombre VARCHAR2(100) NOT NULL,        -- Nombre del usuario
    
contrasena VARCHAR2(100) NOT NULL,    -- Contraseña del usuario
    rol NUMBER(2) NOT NULL               -- Rol del usuario (entero)
);
select * from usuario;
INSERT INTO usuario (nombre, contrasena, rol)
VALUES ('paco', '1234', 0);



elect * from cliente;
drop table cliente;
CREATE TABLE cliente (
    codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- Identificador único automático
    nombre       VARCHAR2(50),
    apellido     VARCHAR2(50),
    ciudad       VARCHAR2(50),
    pais         VARCHAR2(50),
    telefono     VARCHAR2(20),
    hora_d       VARCHAR2(20),
    hora_s       VARCHAR2(20),
    huesped_tipo VARCHAR2(50),
    PRIMARY KEY (codigo) -- Llave primaria
);


select * from cliente;
drop table cliente;